name: Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  docs-checks:
    uses: canonical/operator-workflows/.github/workflows/docs.yaml@main
    secrets: inherit
    with:
      vale-files: '["*.md", "falco-operator/**/*.md", "falcosidekick-k8s-operator/**/*.md", "interfaces/**/*.md"]'
      linkcheck-fail-on-error: false
