name: Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  docs-checks:
    uses: canonical/operator-workflows/.github/workflows/docs.yaml@main
    secrets: inherit
    with:
      vale-files: '["README.md", "SECURITY.md", "CONTRIBUTING.md", "falco-operator", "falcosidekick-k8s-operator"]'
      linkcheck-fail-on-error: false
